name: Build VibeBridge CLI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build with macOS 15 (Latest Xcode)
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Show Swift version
      run: swift --version
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build VibeBridge
      run: swift build -c release
      
    - name: Run tests
      run: swift test
      
    - name: Test CLI help
      run: |
        echo "Testing CLI help output..."
        .build/release/vibebridge || echo "CLI executed (expected to show usage)"
        
    - name: Show build artifacts
      run: |
        echo "Build completed successfully!"
        echo "Executable location: .build/release/vibebridge"
        ls -la .build/release/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vibebridge-cli
        path: .build/release/vibebridge
        retention-days: 30 